SELECT a.CAR_ID AS CAR_ID, ROUND(AVG(a.DURATION), 1) AS AVERAGE_DURATION
FROM
(
SELECT CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)as a
GROUP BY a.CAR_ID
HAVING ROUND(AVG(a.DURATION), 1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

