SELECT CONCAT(A.QUARTER, 'Q') AS QUARTER,
       COUNT(*) AS ECOLI_COUNT
FROM (
  SELECT
    CASE
      WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 1 AND 3  THEN 1
      WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 4 AND 6  THEN 2
      WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 7 AND 9  THEN 3
      WHEN MONTH(DIFFERENTIATION_DATE) BETWEEN 10 AND 12 THEN 4
    END AS QUARTER
  FROM ECOLI_DATA
) AS A
GROUP BY A.QUARTER
ORDER BY A.QUARTER;
