SELECT I.ITEM_ID AS ITEM_ID, I.ITEM_NAME AS ITEM_NAME, I.RARITY AS RARITY
FROM
(
SELECT ITEM_ID
FROM  ITEM_TREE T
WHERE PARENT_ITEM_ID 
IN(
SELECT ITEM_ID
FROM ITEM_INFO
WHERE RARITY = 'RARE')
)A INNER JOIN ITEM_INFO I
ON A.ITEM_ID = I.ITEM_ID
ORDER BY ITEM_ID DESC;
